{"@timestamp":"2018-08-31T01:50:54.739Z","source_host":"central.livngds.com","file":"BatchingBatch.java","method":"performExecution","level":"ERROR","line_number":"141","thread_name":"Thread-45","@version":1,"logger_name":"org.hibernate.engine.jdbc.batch.internal.BatchingBatch","message":"HHH000315: Exception executing batch [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]","class":"org.hibernate.engine.jdbc.batch.internal.BatchingBatch","mdc":{}}
