{"exception":{"stacktrace":"java.io.InterruptedIOException: Interrupted while waiting for response\n\tat org.voltdb.client.ClientImpl.internalSyncCallProcedure(ClientImpl.java:477)\n\tat org.voltdb.client.ClientImpl.callProcedureWithClientTimeout(ClientImpl.java:319)\n\tat org.voltdb.client.ClientImpl.callProcedure(ClientImpl.java:255)\n\tat com.livngds.gds.persistence.volt.dao.DbCacheDaoVoltImpl.getUsableCacheDatas(DbCacheDaoVoltImpl.java:1251)\n\tat com.livngds.gds.persistence.volt.service.CacheDataService.getUsableCacheDatas(CacheDataService.java:259)\n\tat com.livngds.gds.persistence.volt.service.CacheDataService.getUsableCacheDatas(CacheDataService.java:265)\n\tat com.livngds.gds.connect.updater.RatesUpdateOnCentralFromCacheSteps.updateBookableProductFromCache(RatesUpdateOnCentralFromCacheSteps.java:318)\n\tat com.livngds.gds.connect.updater.RatesUpdateOnCentralFromCacheSteps.updateTourFromCache(RatesUpdateOnCentralFromCacheSteps.java:72)\n\tat com.livngds.gds.connect.cache.CacheProcessor$2.run(CacheProcessor.java:480)","exception_class":"java.io.InterruptedIOException","exception_message":"Interrupted while waiting for response"},"source_host":"central.livngds.com","method":"getUsableCacheDatas","level":"ERROR","message":"DbCacheDaoVoltImpl: Error before or during commit. \nProcedure: livngds_getUsableCacheDataByOpCidAndProdCidWithLimit \nParameters: [930, 58213, [1, 2, 3, 4], 1.5, 432000.0, 1.1, 432000.0, 0, 400]","mdc":{},"@timestamp":"2018-09-03T16:04:16.281Z","file":"DbCacheDaoVoltImpl.java","line_number":"1259","thread_name":"CacheProcessor._displayRatesAndOpDaysUpdaterThread","@version":1,"logger_name":"com.livngds.gds.persistence.volt.dao.DbCacheDaoVoltImpl","class":"com.livngds.gds.persistence.volt.dao.DbCacheDaoVoltImpl"}
